plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '8.3.1'
}

group = 'be.yvanmazy'
version = '1.1'

repositories {
    mavenCentral()
}

dependencies {
    // Code style
    api 'org.jetbrains:annotations:24.1.0'

    // Logging
    api 'org.tinylog:slf4j-tinylog:2.7.0'
    api 'org.tinylog:tinylog-impl:2.7.0'

    // Arguments
    api 'org.jcommander:jcommander:2.0'

    // Json
    api 'com.google.code.gson:gson:2.12.1'

    // Byte code
    api 'net.md-5:SpecialSource:1.11.4'
    api 'org.vineflower:vineflower:1.11.0'

    // Testing
    testImplementation platform('org.junit:junit-bom:5.10.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

shadowJar {
    manifest {
        attributes 'Main-Class': 'be.yvanmazy.minecraftremapper.Main'
    }
    archiveClassifier.set('')
}

test {
    useJUnitPlatform()
}